<a href="https://colab.research.google.com/github/JoelByron/AI_Camp_TalentoTech/blob/main/notebooks/09_iIntroduccion_Keras_en_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ejemplo de Tokenización

con keras

In [ ]:
import keras
import tensorflow as tf
from nltk.tokenize import word_tokenize


In [ ]:
frases = ['Hola mundo', 'Hola a todos', 'Hola a todo el mundo ']


In [ ]:
# Genera el diccionario de tokens
tokenizar = tf.keras.preprocessing.text.Tokenizer(num_words=10) # 10 palabras más comunes
tokenizar.fit_on_texts(frases) # Crea el diccionario
word_index = tokenizar.word_index

print('word_index =', word_index)

word_index = {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}


In [ ]:
#Generación de secuencia tokenizadas

secuencias = tokenizar.texts_to_sequences(frases) # convierte fraces a secuencia de tokens
print('secuencias =', secuencias)

secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]


In [ ]:
# Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias) # rellena con 0 hasta alcanzar la sencuia de la longitud mas larga
print('relleno =', relleno)

relleno = [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


In [ ]:
frases = ['Hola mundo', 'Hola a todos', 'Hola a todo el mundo ','Buen día, comó estas hoy?']

In [ ]:
# Genera el diccionario de tokens
tokenizar = tf.keras.preprocessing.text.Tokenizer(num_words=10) # 10 palabras más comunes
tokenizar.fit_on_texts(frases) # Crea el diccionario
word_index = tokenizar.word_index

print('word_index =', word_index)

word_index = {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6, 'buen': 7, 'día': 8, 'comó': 9, 'estas': 10, 'hoy': 11}


In [ ]:
#Generación de secuencia tokenizadas

secuencias = tokenizar.texts_to_sequences(frases) # convierte fraces a secuencia de tokens
print('secuencias =', secuencias)

secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2], [7, 8, 9]]


In [ ]:
# Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias) # rellena con 0 hasta alcanzar la sencuia de la longitud mas larga
print('relleno =\n', relleno)

relleno =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]
 [0 0 7 8 9]]


Ejemplo de Tokenización

con keras

In [ ]:
frases = ['Hola mundo', 'Hola a todos', 'Hola a todo el mundo ','Buen día, comó estas hoy?']

In [ ]:
# Genera el diccionario de tokens
tokenizar = tf.keras.preprocessing.text.Tokenizer(num_words=10, oov_token="<OOV>") # 10 palabras más comunes
tokenizar.fit_on_texts(frases) # Crea el diccionario
word_index = tokenizar.word_index

print('word_index =', word_index)

word_index = {'<OOV>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'día': 9, 'comó': 10, 'estas': 11, 'hoy': 12}


In [ ]:
#Generación de secuencia tokenizadas

secuencias = tokenizar.texts_to_sequences(frases) # convierte fraces a secuencia de tokens
print('secuencias =', secuencias)

secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]


In [ ]:
# Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias) # rellena con 0 hasta alcanzar la sencuia de la longitud mas larga
print('relleno =', relleno)

relleno = [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


In [ ]:
#'pre': Trunca la secuencia desde el principio, es decir, elimina los elementos de la secuencia al principio.
#'post': Trunca la secuencia desde el final, es decir, elimina los elementos de la secuencia al final

# Rellena las secuencias a una longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias,padding = 'post', truncating = 'post') # rellena con 0 hasta alcanzar la sencuia de la longitud mas larga
print('relleno =', relleno)

relleno = [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
